DerethForever.Web/Controllers/RecipeController.cs
/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using System;
using System.IO;
using System.Text;
using System.Web;
using System.Web.Mvc;

using log4net;
using Newtonsoft.Json;

using Lifestoned.DataModel.Gdle.Recipes;
using Lifestoned.Providers;

namespace DerethForever.Web.Controllers
{
    public class RecipeController : BaseController
    {
        private static readonly ILog log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        [HttpGet]
        public ActionResult Index()
        {
            return View(ContentProviderHost.CurrentRecipeProvider.Get());
        }

        [HttpGet]
        public ActionResult Get(uint id)
        {
            Recipe model = ContentProviderHost.CurrentRecipeProvider.Get(id);
            return JsonGet(model, true);
        }

        [HttpPut]
        [Authorize(Roles = "Admin")]
        public ActionResult Put([ModelBinder(typeof(JsonNetModelBinder))]Recipe model)
        {
            model.LastModified = DateTime.Now;
            model.ModifiedBy = GetUserName();

            try
            {
                ContentProviderHost.CurrentRecipeProvider.Save(model);
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.OK);
            }
            catch (Exception ex)
            {
                log.Error($"Error Saving Recipe {model.Key} - {model.Description}", ex);
            }

            return new HttpStatusCodeResult(System.Net.HttpStatusCode.InternalServerError, "Save Failed");
        }

        [HttpGet]
        public ActionResult Edit(uint? id)
        {
            return View(id);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(uint id)
        {
            return View(ContentProviderHost.CurrentRecipeProvider.Get(id));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(Recipe model)
        {
            ContentProviderHost.CurrentRecipeProvider.Delete(model.Key);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult UploadItem()
        {
            string fileNameCopy = "n/a";

            try
            {
                foreach (string fileName in Request.Files)
                {
                    fileNameCopy = fileName;
                    HttpPostedFileBase file = Request.Files[fileName];
                    uint id = 0;

                    using (MemoryStream memStream = new MemoryStream())
                    {
                        file.InputStream.CopyTo(memStream);
                        byte[] data = memStream.ToArray();

                        string serialized = Encoding.UTF8.GetString(data);
                        Recipe item = JsonConvert.DeserializeObject<Recipe>(serialized);
                        id = item.Key;

                        string token = GetUserToken();

                        item.LastModified = DateTime.Now;
                        item.ModifiedBy = GetUserName();

                        // save it
                        ContentProviderHost.CurrentRecipeProvider.Save(item);
                    }
                }
            }
            catch (Exception ex)
            {
                log.Error($"Error parsing uploaded file {fileNameCopy}.", ex);
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            return new EmptyResult();
        }

        [HttpGet]
        public ActionResult DownloadOriginal(uint id)
        {
            try
            {
                Recipe model = ContentProviderHost.CurrentRecipeProvider.Get(id);
                return DownloadJson(model, model.Key, model.Description);
            }
            catch (Exception ex)
            {
                log.Error($"Error exporting recipe {id}", ex);
                return RedirectToAction("Index");
            }
        }
    }
}

DerethForever.Web/Views/Recipe/Delete.cshtml
@using DerethForever.Web.Controllers;
@using Lifestoned.DataModel.Gdle.Recipes;
@using Lifestoned.DataModel.Shared;
@model Recipe

@{
    ViewBag.Title = "Delete " + Model.Description;
}

<br />

<h4>Confirm deletion of @(Html.Raw(Model.Description)), @(Html.Raw(Model.Key))?</h4>

<br />

@using (Html.BeginForm("Delete", "Recipe", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Key)

    <button class="btn btn-danger" id="btnDelete">Delete</button>
    <button class="btn btn-warning" id="btnCancel">Cancel</button>
}

@section scripts {
    <script language="javascript">
        $("#btnDelete").on("click", function () {
            $("form").submit();
        });

        $("#btnCancel").on("click", function () {
            location.href = '@(Url.Action("Index"))';
        });
    </script>
}

DerethForever.Web/Views/Recipe/Edit.cshtml
@using DerethForever.Web.Controllers;
@using Lifestoned.DataModel.Gdle.Recipes;
@model uint?

@{
    ViewBag.Title = "Edit Recipe";
}

<br />

@using (Html.BeginForm("Edit", "Recipe", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="btn-toolbar stuck">
        <div class="btn-group-vertical" role="group">
            <button id="btnSave" type="button" class="btn btn-primary" title="Save"><i class="glyphicon glyphicon-floppy-save"></i></button>
            <a href="@Url.Action("Edit", "Recipe", new { id = Model })" class="btn btn-primary" title="Cancel"><i class="glyphicon glyphicon-remove"></i></a>
            @if (User.IsInRole("Admin"))
            {
                <a href="@Url.Action("Delete", "Recipe", new { id = Model })" class="btn btn-primary" title="Delete"><i class="glyphicon glyphicon-trash"></i></a>
            }
        </div>

        <ul class="btn-group-vertical nav" role="group">
            <li><a data-toggle="tab" href="#general" class="btn btn-primary" title="General Properties"><i class="glyphicon glyphicon-list"></i></a></li>
            <li><a data-toggle="tab" href="#reqs" class="btn btn-primary" title="Requirements"><i class="glyphicon glyphicon-check"></i></a></li>
            <li><a data-toggle="tab" href="#mods" class="btn btn-primary" title="Mods"><i class="glyphicon glyphicon-wrench"></i></a></li>

            <li><a data-toggle="tab" href="#precursors" class="btn btn-primary" title="Precursors"><i class="glyphicon glyphicon-random"></i></a></li>
            <li><a data-toggle="tab" href="#history" class="btn btn-primary" title="Change Log / History"><i class="glyphicon glyphicon-calendar"></i></a></li>
        </ul>
    </div>

    <div id="app" class="form-horizontal">
        <lsd-recipe ref="recipe" recipe-id="@(Model)"></lsd-recipe>
    </div>

}

@section scripts {
    @Scripts.Render("~/bundles/vue", "~/ui/shared", "~/ui/recipe")
    
    <script>
        Vue.use(RecipeStore);
        var recipeStore = makeRecipeService(@(Model));

        var app = new Vue({
            el: '#app',
            recipeStore: recipeStore
        });

        function validate() {
            var valid = $('form')[0].reportValidity();
            if (!valid) {
                alert('Please correct data errors before saving');
            }
            return valid;
            //var cl = recipeStore.recipe.userChangeSummary;
            //if (!cl || cl.length == 0) {
            //    $("a[href='#history']").click();
            //    alert("Update Change Log before saving");
            //    return false;
            //} else {
            //    return true;
            //}
            //return true;
        }

        $(document).ready(function () {
            $('#btnSave').click(function (e) {
                if (validate())
                    recipeStore.save();

                e.preventDefault();
                e.stopPropagation();
            });
        });
    </script>
}

DerethForever.Web/Views/Recipe/Index.cshtml
@model IEnumerable<Lifestoned.DataModel.Gdle.Recipes.Recipe>

@{
    ViewBag.Title = "Recipe Search";
}

<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <table class="table table-striped table-bordered table-hover table-condensed">
        <thead>
            <tr>
                <th>Id</th>
                <th>Description</th>
                <th>Last Modified</th>
                <th style="width: 16rem; text-wrap:none;">Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model == null || Model.Count() == 0)
            {
                <tr><td colspan="4" align="center">No results.</td></tr>
            }
            @{
                foreach (var recipe in Model)
                {
                <tr>
                    <td>@recipe.Key.ToString()</td>
                    <td>@recipe.Description</td>
                    <td>@recipe.LastModified</td>
                    <td>
                        <div class="btn-group" role="group">
                            <a class="btn btn-sm btn-secondary" href="@Url.Action("Edit", "Recipe", new {id = recipe.Key})">
                                <span class="glyphicon glyphicon-edit" title="Edit"></span>
                            </a>
                            <a disabled class="btn btn-sm btn-secondary" href="@Url.Action("Clone", "Recipe", new {id = recipe.Key})">
                                <span class="glyphicon glyphicon-copy" title="Clone"></span>
                            </a>

                            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                            {
                                <a class="btn btn-sm btn-secondary" href="@Url.Action("Delete", "Recipe", new { id = recipe.Key })">
                                    <span class="glyphicon glyphicon-remove" title="Delete"></span>
                                </a>
                            }

                            <div class="btn-group dropdown" role="group">
                                <button class="btn btn-sm btn-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true"><span class="glyphicon glyphicon-download" title="Download"></span>&nbsp;<span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                    <li><a href="@Url.Action("DownloadOriginal", "Recipe", new {id = recipe.Key})">Original</a></li>
                                </ul>
                            </div>
                        </div>
                    </td>

                </tr>
                }
            }
        </tbody>
    </table>

}

DerethForever.Web/Views/Recipe/Upload.cshtml
@{
    ViewBag.Title = "Upload GDLE Recipe Json";
}

<div class="form-horizontal">
    <h2>
        Upload Recipe JSON File
    </h2>
    <hr />

    <p>
        Using this page you can upload <a href="#" data-toggle="tooltip" title="Intended to import/modify originally generated content from the GDLE emulator, not for use importing or modifying copyright protected content.">GDLE Recipe json files</a> of 1 recipe each.
        After upload, you can download it from the @Html.ActionLink("Sandbox", "Index", "Sandbox") page.
    </p>
    <br />

    <div class="well">
        <form id="dz" action="@Url.Action("UploadItem", "Recipe")" class="dropzone"></form>
    </div>
</div>

@section scripts {
    <script language="javascript">
        Dropzone.options.dz = {

            acceptedFiles: 'application/json',
            addRemoveLinks: true,
            parallelUploads: 5,
            params: function () {
            },
            init: function () {
                var $this = this;

                $this.on('addedfile', function () {
                });

                $this.on('success', function (file) {
                    $this.removeFile(file);
                });

                $this.on('queueComplete', function () {
                });
            },
            dictResponseError: "Upload Failed {{statusCode}}"
        };
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
}