DerethForever.Web/Controllers/SpawnController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Lifestoned.DataModel.Gdle.Spawns;
using Lifestoned.Providers;
using log4net;
using Newtonsoft.Json;

namespace DerethForever.Web.Controllers
{
    public class SpawnController : BaseController
    {
        private static readonly ILog log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        // GET: Spawn
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Map(uint id)
        {
            SpawnMapChange change = SandboxContentProviderHost.CurrentProvider.GetLandblockChange(id);
            if (change != null)
                return JsonGet(change.Entry);
            return JsonGet(SandboxContentProviderHost.CurrentProvider.GetLandblock(id));
        }

        public ActionResult Search(string query)
        {
            return JsonGet(SandboxContentProviderHost.CurrentProvider.SearchLandblocks(query));
        }

        [Authorize]
        [HttpPost]
        public ActionResult New(SpawnMapEntry map)
        {
            if (SandboxContentProviderHost.CurrentProvider.GetLandblock(map.Key) != null)
                return Json(null);

            SandboxContentProviderHost.CurrentProvider.SaveLandblock(map);
            return Json(map);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Save(SpawnMapEntry map)
        {
            SandboxContentProviderHost.CurrentProvider.SaveLandblock(map);
            return RedirectToAction("Index", "Sandbox");
        }

        [HttpGet]
        public ActionResult Download(uint id, string userGuid = null)
        {
            SpawnMapEntry map = null;

            if (!string.IsNullOrWhiteSpace(userGuid))
            {
                // id specified: is it us, or are we an admin
                if (string.Compare(userGuid, GetUserGuid(), true) == 0 || User.IsInRole("Developer"))
                {
                    SpawnMapChange change = SandboxContentProviderHost.CurrentProvider.GetLandblockChange(id, userGuid);
                    map = change.Entry;
                }
            }
            else
            {
                map = ContentProviderHost.CurrentProvider.GetLandblock(id);
            }

            if (map == null)
                return new HttpNotFoundResult();

            JsonSerializerSettings s = new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore };
            string content = JsonConvert.SerializeObject(map, Formatting.None, s);
            string name = map.Description;
            foreach (char ifn in System.IO.Path.GetInvalidFileNameChars())
                name = name.Replace(ifn, '_');

            string filename = $"{name}.json";
            return File(Encoding.UTF8.GetBytes(content), "application/json", filename);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult UploadItem()
        {
            string fileNameCopy = "n/a";

            try
            {
                foreach (string fileName in Request.Files)
                {
                    fileNameCopy = fileName;
                    HttpPostedFileBase file = Request.Files[fileName];
                    uint id = 0;

                    using (MemoryStream memStream = new MemoryStream())
                    {
                        file.InputStream.CopyTo(memStream);
                        byte[] data = memStream.ToArray();

                        string serialized = Encoding.UTF8.GetString(data);
                        SpawnMapEntry item = JsonConvert.DeserializeObject<SpawnMapEntry>(serialized);
                        id = item.Key;

                        string token = GetUserToken();

                        item.LastModified = DateTime.Now;
                        item.ModifiedBy = GetUserName();

                        // save it
                        SandboxContentProviderHost.CurrentProvider.SaveLandblock(item);
                    }
                }
            }
            catch (Exception ex)
            {
                log.Error($"Error parsing uploaded file {fileNameCopy}.", ex);
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            return new EmptyResult();
        }

        [Authorize(Roles = "Developer")]
        [HttpGet]
        public ActionResult Compile()
        {
            SpawnMap map = new SpawnMap();

            foreach (SpawnMapEntry entry in ContentProviderHost.CurrentProvider.GetLandblocks())
            {
                map.Entries.Add(entry);
            }

            string now = DateTime.UtcNow.ToString();
            map.Comment = $"Created by {GetUserName()} at {now}";

            JsonSerializerSettings s = new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore };
            string content = JsonConvert.SerializeObject(map, Formatting.None, s);

            string name = $"worldspawns-{now}";
            foreach (char ifn in System.IO.Path.GetInvalidFileNameChars())
                name = name.Replace(ifn, '_');

            string filename = $"{name}.json";
            return File(Encoding.UTF8.GetBytes(content), "application/json", filename);
        }
    }
}

DerethForever.Web/Controllers/WeenieController.cs
/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using DerethForever.Web.Models.Discord;
using log4net;
using Lifestoned.DataModel.Gdle;
using Newtonsoft.Json;
using RestSharp;
using Lifestoned.DataModel.Shared;
using Lifestoned.DataModel.Account;
using Lifestoned.Providers;

namespace DerethForever.Web.Controllers
{
    public class WeenieController : BaseController
    {
        private const string _Session_IndexModel = "__weenieIndexModel";
        private const string _Session_DownloadModel = "__weenieDownloadModel";

        private static readonly ILog log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public IndexModel CurrentIndexModel
        {
            get { return (IndexModel)Session[_Session_IndexModel]; }
            set { Session[_Session_IndexModel] = value; }
        }

        public DownloadChangeModel CurrentDownload
        {
            get { return (DownloadChangeModel)Session[_Session_DownloadModel]; }
            set { Session[_Session_DownloadModel] = value; }
        }

        private Weenie GetWeenieForUser(uint id, string userGuid)
        {
            WeenieChange wc = null;
            ViewBag.UserGuid = null;
            string userToken = GetUserToken();

            if (!string.IsNullOrEmpty(userToken))
            {
                if (string.IsNullOrWhiteSpace(userGuid))
                {
                    // no userGuid specified, assume your own sandbox
                    wc = SandboxContentProviderHost.CurrentProvider.GetMySandboxedChange(GetUserToken(), id);
                }
                else
                {
                    // validate dev/admin or matches your id
                    if (User.IsInRole("Developer") || GetUserGuid() == userGuid)
                        wc = SandboxContentProviderHost.CurrentProvider.GetSandboxedChange(Guid.Parse(userGuid), id);
                    else
                        return null;
                }
            }

            Weenie weenie = null;
            if (wc != null)
            {
                weenie = wc.Entry;
                ViewBag.UserGuid = userGuid;
            }
            else
                weenie = SandboxContentProviderHost.CurrentProvider.GetWeenie(GetUserToken(), id);

            return weenie;
        }

        [HttpGet]
        public ActionResult SpellList()
        {
            return View("SpellListPopup");
        }

        [HttpGet]
        public ActionResult Recent()
        {
            IndexModel model = CurrentIndexModel ?? new IndexModel();
            model.Results = SandboxContentProviderHost.CurrentProvider.RecentChanges(GetUserToken());

            return View(model);
        }

        [HttpGet]
        public ActionResult AllUpdates()
        {
            var allUpdates = SandboxContentProviderHost.CurrentProvider.AllUpdates(GetUserToken());
            var zipFile = new ZipFile();
            foreach (var update in allUpdates)
            {
                // build the CachePwn json for this weenie
                var weenie = SandboxContentProviderHost.CurrentProvider.GetWeenie(GetUserToken(), update.WeenieClassId);
                // var cachePwn = Weenie.ConvertFromWeenie(weenie);
                var settings = new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore };
                var contents = JsonConvert.SerializeObject(weenie, Formatting.None, settings);

                // build filename
                var name = weenie.Name;
                var removeChars = new List<string>() { "\t", "\n", "!", "\"" };
                foreach (var removeChar in removeChars)
                    name = name.Replace(removeChar, "");

                var filename = $"{update.WeenieClassId} - {name}.json";

                // add json to zip file
                zipFile.AddFile(filename, contents);
            }

            var bytes = zipFile.BuildZip();
            string date = string.Format("{0:yyyy-MM-dd_hh-mm}", DateTime.Now);
            return File(bytes, "application/zip", "GDLE-Latest-Updates-" + date + ".zip");
        }

        [HttpGet]
        public ActionResult Detail(uint id, string userGuid)
        {
            Weenie weenie = GetWeenieForUser(id, userGuid);

            if (weenie == null)
                return new HttpNotFoundResult();

            return View(weenie);
        }

        [HttpGet]
        public ActionResult Index()
        {
            IndexModel model = CurrentIndexModel ?? new IndexModel();
            BaseModel current = CurrentBaseModel;
            BaseModel.CopyBaseData(current, model);
            CurrentBaseModel = current;

            return View(model);
        }

        [HttpPost]
        public ActionResult Index(IndexModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            try
            {
                string token = GetUserToken();

                model.Results = SandboxContentProviderHost.CurrentProvider.WeenieSearch(token, model.Criteria);

                if (!string.IsNullOrEmpty(token))
                {
                    List<WeenieChange> mine = SandboxContentProviderHost.CurrentProvider.GetMyWeenieChanges(GetUserToken());
                    model.Results.ForEach(w =>
                    {
                        if (mine.Any(m => m.Entry.WeenieClassId == w.WeenieClassId))
                            w.HasSandboxChange = true;
                    });
                }

                model.ShowResults = true;
            }
            catch (Exception ex)
            {
                model.Results = null;
                model.ShowResults = false;
                model.ErrorMessages.Add("Error retrieving data from the SandboxContentProviderHost");
                model.Exception = ex;
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult Get(uint id, string userGuid)
        {
            Weenie weenie = GetWeenieForUser(id, userGuid);

            if (weenie == null)
                return new HttpNotFoundResult();

            SortTheThings(weenie);
            return JsonGet(weenie);
        }

        [HttpPut]
        [Authorize]
        public ActionResult Put(Weenie model)
        {
            ModelState.Clear();
            // TODO: Better Validation
            ActionResult result = ValidateWeenie(model);

            if (result != null)
            {
                ModelState.Clear();
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.InternalServerError, "Validation Failed");
            }

            model.CleanDeletedAndEmptyProperties();
            model.LastModified = DateTime.Now;
            model.ModifiedBy = GetUserName();

            try
            {
                SandboxContentProviderHost.CurrentProvider.UpdateWeenie(GetUserToken(), model);

                IndexModel indexModel = new IndexModel();
                indexModel.SuccessMessages.Add("Weenie " + model.WeenieClassId.ToString() + " successfully saved.");
                CurrentIndexModel = indexModel;

                ////return SandboxAction();
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.OK);
            }
            catch (Exception ex)
            {
                model.ErrorMessages.Add("Error saving weenie in the API");
                model.Exception = ex;
            }

            return new HttpStatusCodeResult(System.Net.HttpStatusCode.InternalServerError, "Save Failed");
        }

        [HttpGet]
        ////[Authorize]
        public ActionResult Edit(uint id)
        {
            Weenie model = SandboxContentProviderHost.CurrentProvider.GetWeenie(GetUserToken(), id);
            SortTheThings(model);
            return View(model);
        }

        private void SortTheThings(Weenie model)
        {
            if (model == null)
                return;

            var deprecatedWeenieTypeProperty = model.IntStats.FirstOrDefault(ip => ip.Key == 9007);
            if (deprecatedWeenieTypeProperty != null)
                model.IntStats.Remove(deprecatedWeenieTypeProperty);

            // Setting sort order for edit
            model.IntStats = model.IntStats.OrderBy(ip => ip.Key).ToList();
            model.FloatStats = model.FloatStats.OrderBy(dp => dp.Key).ToList();
        }

        [HttpGet]
        [Authorize]
        public ActionResult Clone(uint id, string userGuid)
        {
            Weenie weenie = GetWeenieForUser(id, userGuid);

            if (weenie == null)
                return new HttpNotFoundResult();

DerethForever.Web/Views/Shared/DisplayTemplates/ChangeDiscussionEntry.cshtml
@model Lifestoned.DataModel.Shared.ChangeDiscussionEntry

<div class="panel panel-default">
    <div class="panel-heading">
        @Html.Raw(Html.Encode(Model.UserName + " on " + Model.Created.ToString("g")))
    </div>
    <div class="panel-body text-prewrap">@Html.Raw(Html.Encode(Model.Comment))</div>
</div>

DerethForever.Web/Views/Shared/DisplayTemplates/ChangeDiscussionList.cshtml
@model List<Lifestoned.DataModel.Shared.ChangeDiscussionEntry>

<div class="panel panel-default">
    <div class="panel-heading">
        <a href="#@(Html.IdFor(m => m))" data-toggle="collapse" aria-expanded="false">Discussion</a>
    </div>
    <div id="@(Html.IdFor(m => m))" class="panel-collapse collapse panel-body">
        <div class="panel-group">
            @for (int i = 0; i < Model.Count(); i++)
            {
                @Html.DisplayFor(m => Model[i])
            }

            @if ((Model?.Count() ?? 0) == 0)
            {
                <p>No comments.</p>
            }
        </div>
        <div class="col-sm-10">
            <button type="button" class="btn btn-primary"
                    data-toggle="modal" data-target="#modal-discussion"
                    data-user="@(ViewData["UserGuid"])" data-item="@(ViewData["EntryId"])" data-type="@(ViewData["EntryType"])">
                Add Comment
            </button>
        </div>

    </div>

</div>

DerethForever.Web/Views/Shared/DisplayTemplates/ChangeEntries.cshtml
@model List<Lifestoned.DataModel.Shared.ChangeEntry>

@if (Model == null || Model.Count() < 1)
{
    <div class="alert alert-info">
        There are no changes to review.
    </div>
}
else
{
    <div class="entries">
        @{
            for (int i = 0; i < Model.Count(); i++)
            {
                @Html.DisplayFor(m => Model[i]);
            }
        }

    </div>

}

DerethForever.Web/Views/Shared/DisplayTemplates/Changelog.cshtml
@model List<Lifestoned.DataModel.Shared.ChangelogEntry>

@for (int i = 0; i < (Model?.Count ?? 0); i++)
{
    @Html.HiddenFor(m => m[i].Created)
    @Html.HiddenFor(m => m[i].Author)
    @Html.HiddenFor(m => m[i].Comment)
    <div class="row row-spacer">
        <div class="col-md-10">
            <div class="panel panel-default">
                <div class="panel-heading">
                    @Html.Raw(Html.Encode(Model[i].Author + " on " + Model[i].Created.ToString("g")))
                </div>
                <div class="panel-body text-prewrap">
                    @Html.Raw(Html.Encode(Model[i].Comment))
                </div>
            </div>
        </div>
    </div>
}

DerethForever.Web/Views/Shared/DisplayTemplates/DateTime.cshtml
@model System.DateTime?

@if (Model != null)
{
    <span>@Html.Raw(Model.Value.ToString("yyyy-MM-dd HH:mm"))</span>
}

DerethForever.Web/Views/Shared/DisplayTemplates/InfoMessages.cshtml
@model Lifestoned.DataModel.Shared.BaseModel

@if (Model?.ErrorMessages?.Count > 0)
{
    <div class="alert alert-danger">
        <ul>
            @for (int i = 0; i < Model.ErrorMessages.Count; i++)
            {
                <li>@Html.DisplayFor(m => m.ErrorMessages[i])</li>
            }
        </ul>
        @if (Model.Exception != null)
        {
            <pre>@Html.DisplayFor(m => m.Exception)</pre>
        }
    </div>
}

@if (Model?.InfoMessages?.Count > 0)
{
    <div class="alert alert-info">
        <ul>
            @for (int i = 0; i < Model.InfoMessages.Count; i++)
            {
                <li>@Html.DisplayFor(m => m.InfoMessages[i])</li>
            }
        </ul>
    </div>
    <hr />
}

@if (Model?.SuccessMessages?.Count > 0)
{
    <div class="alert alert-success">
        <ul>
            @for (int i = 0; i < Model.SuccessMessages.Count; i++)
            {
                <li>@Html.DisplayFor(m => m.SuccessMessages[i])</li>
            }
        </ul>
    </div>
    <hr />
}

@if (Model?.WarningMessages?.Count > 0)
{
    <div class="alert alert-warning">
        <ul>
            @for (int i = 0; i < Model.WarningMessages.Count; i++)
            {
                <li>@Html.DisplayFor(m => m.WarningMessages[i])</li>
            }
        </ul>
    </div>
    <hr />
}

DerethForever.Web/Views/Shared/DisplayTemplates/SpawnMapChange.cshtml
@model Lifestoned.DataModel.Gdle.Spawns.SpawnMapChange
@using DerethForever.Web.Controllers

@{ 
    bool IsApproval = ViewData.Where(kv => kv.Key == "IsApproval").FirstOrDefault().Value as bool? ?? false;
}

<div class="well @(!Model.Submitted ? "need-submit" : "submitted")"
     data-id="@(Model.EntryId)"
     data-type="@(Model.EntryType)"
     data-name="@(Model.Entry.Description)"
     data-user="@(Model.UserName)"
     data-date="@(new DateTimeOffset(Model.SubmissionTime.ToUniversalTime()).ToUnixTimeSeconds())">
    <div class="row">
        <div class="col-md-1">
            <div class="icon">
                <img src="@Url.Action("GetImage", "Resource",
                            new { imageId = 0x0600211F }) " />
            </div>
        </div>
        <div class="col-md-6">
            @Html.DisplayFor(m => m.Entry.Description)
            (@Html.DisplayFor(m => m.Entry.Key))<br />
            Submitted by @Html.DisplayFor(m => m.UserName) on @Html.DisplayFor(m => m.SubmissionTimeDisplay)<br />
            <br />
        </div>
        <div class="col-md-5">
            <div class="btn-group">
                @if (!IsApproval)
                {
                    <button type="button" class="btn btn-default btn-sm" @@click="editMap(@Model.Entry.Key)">Edit</button>
                    <div class="btn btn-default btn-sm">@Html.ActionLink("Clone", "Clone", "Spawns", new { id = Model.Entry.Key }, null)</div>
                }
                <div class="btn btn-default btn-sm">
                    <i class="glyphicon glyphicon-download"></i>
                    @Html.ActionLink("Sandbox", "Download", "Spawn", new { id = Model.Entry.Key, userGuid = Model.UserGuid }, null)
                </div>
                <div class="btn btn-default btn-sm">
                    <i class="glyphicon glyphicon-download"></i>
                    @Html.ActionLink("Original", "Download", "Spawn", new { id = Model.Entry.Key }, null)
                </div>

            </div>
            @if (!IsApproval && BaseController.CurrentUser.AccountGuid == Model.UserGuid)
            {
                <div>
                    @if (Model.Submitted)
                    {
                        <button data-id="@(Model.EntryId)" data-type="@(Model.EntryType)" class="sandbox-submit btn btn-sm btn-primary">Withdraw Submission</button>
                    }
                    else
                    {
                        <button data-id="@(Model.EntryId)" data-type="@(Model.EntryType)" class="sandbox-submit btn btn-sm btn-warning">Submit for Review</button>
                    }
                    <button data-id="@(Model.EntryId)" data-type="@(Model.EntryType)" class="sandbox-delete btn btn-sm btn-primary">Delete Changes</button>
                </div>
            }
            @if (IsApproval && User.IsInRole("Developer"))
            {
                <div>
                    <button class="sandbox-approve btn btn-sm btn-primary"
                            data-id="@(Model.EntryId)"
                            data-type="@(Model.EntryType)"
                            data-user="@(Model.UserGuid)">
                        Accept
                    </button>

                    <button class="btn btn-sm btn-warning"
                            data-toggle="modal" data-target="#modal-reject"
                            data-user="@(Model.UserGuid)" data-id="@(Model.EntryId)" data-type="@(Model.EntryType)">
                        Reject
                    </button>
                </div>
            }

        </div>
    </div>
    <br />

    @Html.DisplayFor(m => m.Discussion, new {
        UserGuid = Model.UserGuid,
        EntryId = Model.Entry.Key,
        EntryType = "spawnmap" })

</div>

DerethForever.Web/Views/Shared/DisplayTemplates/WeenieChange.cshtml
@using DerethForever.Web.Controllers
@model Lifestoned.DataModel.Gdle.WeenieChange

@{
    bool IsApproval = ViewData.Where(kv => kv.Key == "IsApproval").FirstOrDefault().Value as bool? ?? false;
}

<div class="well @(!Model.Submitted ? "need-submit" : "submitted")"
     data-id="@(Model.EntryId)"
     data-type="@(Model.EntryType)"
     data-name="@(Model.Entry.Name)"
     data-user="@(Model.UserName)"
     data-date="@(new DateTimeOffset(Model.SubmissionTime.ToUniversalTime()).ToUnixTimeSeconds())">
    <div class="row">
        <div class="col-md-1">
            <div class="icon">
                <img src="@Url.Action("GetDynamicIcon", "Resource",
                            new {
                                itemType = Model.Entry.ItemType,
                                underlayId = Model.Entry.UnderlayId,
                                overlayId = Model.Entry.OverlayId,
                                iconId = Model.Entry.IconId,
                                uiEffects = Model.Entry.UIEffects }) " />
            </div>
        </div>
        <div class="col-md-6">
            @Html.DisplayFor(m => m.Entry.Name)
            (@Html.DisplayFor(m => m.Entry.WeenieClassId))<br />
            Submitted by @Html.DisplayFor(m => m.UserName) on @Html.DisplayFor(m => m.SubmissionTimeDisplay)<br />
            <br />
        </div>
        <div class="col-md-5">
            <div class="btn-group">
                @if (!IsApproval)
                {
                    <div class="btn btn-default btn-sm">@Html.ActionLink("Edit", "Edit", "Weenie", new { id = Model.Entry.WeenieClassId }, null)</div>
                    <div class="btn btn-default btn-sm">@Html.ActionLink("Clone", "Clone", "Weenie", new { id = Model.Entry.WeenieClassId }, null)</div>
                }
                else
                {
                    <div class="btn btn-default btn-sm">@Html.ActionLink("View", "Detail", "Weenie", new { id = Model.Entry.WeenieClassId, userGuid = Model.UserGuid }, null)</div>
                }
                <div class="btn btn-default btn-sm">
                    <i class="glyphicon glyphicon-download"></i>
                    @Html.ActionLink("Sandbox", "DownloadSandbox", "Weenie", new { id = Model.Entry.WeenieClassId, userGuid = Model.UserGuid }, null)
                </div>
                <div class="btn btn-default btn-sm">
                    <i class="glyphicon glyphicon-download"></i>
                    @Html.ActionLink("Original", "DownloadOriginal", "Weenie", new { id = Model.Entry.WeenieClassId }, null)
                </div>

            </div>
            @if (!IsApproval && BaseController.CurrentUser.AccountGuid == Model.UserGuid)
            {
                <div>
                    @if (Model.Submitted)
                    {
                        <button data-id="@(Model.EntryId)" data-type="@(Model.EntryType)" class="sandbox-submit btn btn-sm btn-primary">Withdraw Submission</button>
                    }
                    else
                    {
                        <button data-id="@(Model.EntryId)" data-type="@(Model.EntryType)" class="sandbox-submit btn btn-sm btn-warning">Submit for Review</button>
                    }
                    <button data-id="@(Model.EntryId)" data-type="@(Model.EntryType)" class="sandbox-delete btn btn-sm btn-primary">Delete Changes</button>
                </div>
            }
            @if (IsApproval && User.IsInRole("Developer"))
            {
                <div>
                    <button class="sandbox-approve btn btn-sm btn-primary"
                            data-id="@(Model.EntryId)"
                            data-type="@(Model.EntryType)"
                            data-user="@(Model.UserGuid)">
                        Accept
                    </button>

                    <button class="btn btn-sm btn-warning"
                            data-toggle="modal" data-target="#modal-reject"
                            data-user="@(Model.UserGuid)" data-id="@(Model.EntryId)" data-type="@(Model.EntryType)">
                        Reject
                    </button>
                </div>
            }

        </div>
    </div>
    <br />

    <div class="panel panel-default">
        <div class="panel-heading">
            <a href="#@(Html.IdFor(m => m))" data-toggle="collapse" aria-expanded="false">Change Log Entry</a>
        </div>
        <div id="@(Html.IdFor(m => m))" class="panel-collapse collapse panel-body">
            @Html.Raw(string.IsNullOrEmpty(Model.Entry.UserChangeSummary) ? "None" : Model.Entry.UserChangeSummary)
        </div>

    </div>

    @Html.DisplayFor(m => m.Discussion, new {
        UserGuid = Model.UserGuid,
        EntryId = Model.Entry.WeenieClassId,
        EntryType = "weenie" })

</div>